### ISSUE TITLE
Add requirements and readme

### ISSUE THREAD

**Issue by deepanshu-jain1999** [deepanshu-jain1999/graphql_learning#7]

**Comment by dahiya-code** [comment]
Please assign it to me

**Comment by dahiya-code** [comment]
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

**Comment by deepanshu-jain1999** [comment]
Fixed

**Comment by deepanshu-jain1999** [comment]
> Sir please help me in HACKTOBER FEST 2020
> We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
> Latest guidelines issued by the organizers
> I sincerely hope you will help me
> https://hacktoberfest.digitalocean.com/hacktoberfest-update
> I am attaching the link too for your convenience

Sorry, @navya252001 I just see your comment after pushing.

**Comment by deepanshu-jain1999** [comment]
@navya252001 You can go through this one https://github.com/deepanshu-jain1999/skin_cancer_detection/issues/4

**Comment by dahiya-code** [comment]
Okay
